# Sprite Cloud ceremony

# These are optional but helpful for open-source projects.

github: longjoel
# patreon: # uncomment if you set up Patreon
# ko_fi: # uncomment if you set up Ko-fi
# custom: # custom sponsorship URL
