#!/usr/bin/env bash
set -euo pipefail
# Contract tests for the systemd service generated by scripts/install.sh.
# Guards against regressions in managed binary paths, sandbox writability,
# service-identity preflights, and ownership/mode correctness.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALLER="${REPO_ROOT}/scripts/install.sh"
TMP_HOME="$(mktemp -d)"
trap 'rm -rf "$TMP_HOME"' EXIT

FAILURES=0

fail() {
  printf '  FAIL: %s\n' "$*" >&2
  FAILURES=$((FAILURES + 1))
}

assert_contains() {
  local haystack="$1" needle="$2" label="$3"
  if ! grep -qF "$needle" <<<"$haystack"; then
    fail "$label: expected '$needle' not found in output"
  fi
}

assert_not_contains() {
  local haystack="$1" needle="$2" label="$3"
  if grep -qF "$needle" <<<"$haystack"; then
    fail "$label: found unexpected '$needle'"
  fi
}

# ── Service content (via --print-service) ────────────────────────────────

rootless_svc="$(HOME="$TMP_HOME" bash "$INSTALLER" --rootless --print-service 2>&1)" || true
system_svc="$(bash "$INSTALLER" --print-service 2>&1)" || true

# Rootless service checks
assert_contains "$rootless_svc" "ExecStart=" "rootless: missing ExecStart"
assert_contains "$rootless_svc" "ExecStart=${TMP_HOME}/.local/bin/sc-server" \
  "rootless: ExecStart should point to managed bin dir"

# System-wide service checks
assert_contains "$system_svc" "User=sprite-cloud" "system: missing User"
assert_contains "$system_svc" "Group=sprite-cloud" "system: missing Group"
assert_contains "$system_svc" "ExecStart=/var/lib/sprite-cloud/bin/sc-server" \
  "system: ExecStart should point to managed bin dir"
assert_contains "$system_svc" "ReadWritePaths=/var/lib/sprite-cloud" \
  "system: ReadWritePaths must include DATA_DIR"
assert_contains "$system_svc" "ProtectSystem=strict" \
  "system: ProtectSystem must be strict"
assert_contains "$system_svc" "NoNewPrivileges=yes" \
  "system: NoNewPrivileges must be yes"
assert_not_contains "$system_svc" "ExecStart=/usr/local/bin/sc-server" \
  "system: ExecStart must NOT point to /usr/local/bin"

# ── Preflight: must test writability as the service account ──────────────
# The installer's write probe (non-rootless path) must use runuser or su
# to test as the sprite-cloud user, not just $SUDO touch as root.

installer_src="$(< "$INSTALLER")"

# The preflight block must contain runuser/su targeting sprite-cloud
if ! grep -qP 'runuser\s+.*sprite-cloud' <<<"$installer_src"; then
  if ! grep -qP "su\\s+.*sprite-cloud" <<<"$installer_src"; then
    fail "preflight: write probe must test as sprite-cloud (runuser/su), not just root"
  fi
fi

# The preflight must test a create+delete cycle, not just touch
if ! grep -qF 'rm -f' <<<"$installer_src"; then
  fail "preflight: must clean up probe file after test"
fi

# ── Post-install ownership/mode verification ─────────────────────────────
# After installing binaries, the installer must verify they are owned by
# the service account with executable mode.

if ! grep -qF 'chown' <<<"$installer_src"; then
  fail "ownership: installer must chown binaries to service account"
fi
if ! grep -qE 'chmod\s+0?755|install\s+.*-m\s+0?755' <<<"$installer_src"; then
  fail "ownership: installer must set executable mode (755) on binaries"
fi

# ── Report ───────────────────────────────────────────────────────────────
if (( FAILURES > 0 )); then
  printf '\ninstaller service contract: %d FAILURE(S)\n' "$FAILURES" >&2
  exit 1
fi
printf 'installer service contract: PASS\n'
